# .streamlit/config.toml
[server]
port = 8504
address = "0.0.0.0"
baseUrlPath = "/image-maker"
enableCORS = false
headless = true


# 開発環境 (自分だけで使う場合)
# [server]
# port = 8503
# address = "localhost"
# headless = false

# 社内LAN / サーバー環境 (他のPCからもアクセスする場合)
# [server]
# port = 8503
# address = "0.0.0.0"
# baseUrlPath = "/image-maker"
# headless = true
